---
- name:  created files 
  hosts: localhost
  gather_facts: yes
  tasks: 
    - name: create a file on localhost
      file: 
        name: repo.json
        state: touch
      
    - name: enter some content in json file
      copy:
        content: '"remote_url: https://github.com/adityasai344/ansible-project.git"'
        dest: repo.json
      ignore_errors: yes

    - name: print 'os_family'
      ansible.builtin.debug:
        msg: This is {{ ansible_os_family }} server

    - name: print OS details only if it is rhel
      command: cat /etc/os-release
      when: ansible_os_family == "Debian"
      register: osrelease

    - name: print selinux status only when selinux disabled
      ansible.builtin.command: getenforce
      when: ansible_facts.selinux.status == 'enabled'
      ignore_errors: yes
      

    - name: print os-details
      ansible.builtin.debug:
        var: osrelease
      