---
- name:  created files 
  hosts: localhost
  tasks: 
    - name: create a file on localhost
      file: 
        name: repo.json
        state: touch
    - name: enter some content in json file
      copy:
        content: '"remote_url: https://github.com/adityasai344/ansible-project.git"'
        dest: repo.json
        